# AUTOGENERATED! DO NOT EDIT! File to edit: Economic_Growth.ipynb.

# %% auto 0
__all__ = []

# %% Economic_Growth.ipynb 1
from datetime import datetime

import streamlit as st

from streamlit_jupyter import StreamlitPatcher, tqdm

# %% Economic_Growth.ipynb 3
st.title("Economic Growth")

# %% Economic_Growth.ipynb 4
st.markdown(
    """

GDP per Capita

"""
)

# %% Economic_Growth.ipynb 5
# Import libraries:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import wbgapi as wb
import plotly.graph_objects as go

# %% Economic_Growth.ipynb 8
df = wb.data.DataFrame('NY.GDP.PCAP.CD', time=range(2010, 2020, 2), labels=True)
df

# %% Economic_Growth.ipynb 9
#defining containers
header = st.container()
with header:
    st.title("GDP per capita")
param_lst = list(df.Country)
select_param = st.multiselect('Select Countries to compare', param_lst)
plot_spot = st.empty()

# %% Economic_Growth.ipynb 10
#function to make chart
def make_chart(df,select_param):
    rows_ = df.loc[df.Country.isin(select_param)]
    codes = rows_.index.tolist()
    fig = wb.data.DataFrame('NY.GDP.PCAP.CD', codes,
                     time=range(2010, 2020, 2), index='time')
    st.line_chart(fig)

# %% Economic_Growth.ipynb 11
#func call
with plot_spot:
    make_chart(df, select_param)
